^http[s]?.+ulogs.umeng.com url reject
^http[s]?.+ulogs.umengcloud.com url reject
^http[s]?.+gslbali.ximalaya.com url reject
#^http[s]?.+xmc.ximalaya.com url reject
^http[s]?.+adse.ximalaya.com url reject
^http[s]?.+log1.cmpassport.com url reject
^http[s]?.+sysdk.cl2009.com url reject
^http[s]?.+gslbtx.ximalaya.com url reject
^http[s]?.+t.appsflyer.com url reject
^http[s]?.+location.ximalaya.com url reject
^http[s]?.+passport.ximalaya.com url reject
^http[s]?.+adbehavior.ximalaya.com url reject
^http[s]?.+pv.sohu.com url reject
^http[s]?.+ad.ximalaya.com url reject
^http[s]?.+audid-api.taobao.com url reject
//^http[s]?.+(/ad|/ads|umeng).+ url reject
^http[s]?.+safebrowsing.urlsec.qq.com url reject
^http[s]?.+api-access.pangolin-sdk-toutiao.com url reject
